### ISSUE TITLE
NULL color

### ISSUE THREAD

**Issue by springimport** [phpmyadmin/phpmyadmin#12543]
What about to make a special color for NULL?

![222](https://cloud.githubusercontent.com/assets/18581994/18280343/bf33df00-7426-11e6-8abf-7dc31c6ad276.PNG)
```css
.table_results td i {
    color: #7d7d7d;
}
```

**phpMyAdmin version:** 4.4.15.7

### Client configuration
**Browser:** Google Chrome >50.
**Operating system:** Windows 10 x64.
