### ISSUE TITLE
[regression] Table borders missing on theme original

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#15818]
Since phpMyAdmin 5.0.0, the classic theme lost the borders of the tables, making it a bit "ugly" to look at:

![image](https://user-images.githubusercontent.com/487079/72681586-f3658200-3abc-11ea-9c3e-98722a28c81a.png)

![image](https://user-images.githubusercontent.com/487079/72681612-31fb3c80-3abd-11ea-808a-7193025d0159.png)

I have automated the following addition to CSS on phpMyAdmin upgrades:

```css
.table_results tr, #tablestructure tr, #structureTable tr {
    border-bottom: 1px solid #aaa;
}
```

I'd like to suggest this as official CSS.

Looks like this (much better):

![image](https://user-images.githubusercontent.com/487079/72681604-15f79b00-3abd-11ea-916e-7aef7663a8a8.png)

![image](https://user-images.githubusercontent.com/487079/72681610-2a3b9800-3abd-11ea-8fd6-d2ddeea650e6.png)

**Comment by williamdes** [comment]
@nunoperalta adding
```css
table {
  border-collapse: separate;
}
```

Fixes the issue, do I commit that for next version ?
