### ISSUE TITLE
controlhost being ignored

### ISSUE THREAD

**Issue by stalks** [phpmyadmin/phpmyadmin#15853]
I have a docker environment with several mysql databases that I wish to manage from a single phpmyadmin instance. I wish to use a central controlhost so I don't need a pma database on each sql instance. I have set controlhost = <centralserver> on all servers, however when I visit all but the server hosting the pma control database I don't get the features that a control database offers.

Example server config _(sanitized var_dump($cfg)_:
```{
  ["Servers"]=>
    {
    [1]=>
      {
      ["host"]=> "nginx-sql"
      ["verbose"]=> ""
      ["port"]=> ""
      ["auth_type"]=> "cookie"
      ["controlhost"]=> "nginx-sql"
      ["controluser"]=> "phpmyadmin"
      ["controlpass"]=> "password"
      ["compress"]=> bool(false)
      ["AllowNoPassword"]=> bool(true)
    }
    [2]=>
      {
      ["host"]=> "gitea-sql"
      ["verbose"]=> ""
      ["port"]=> ""
      ["auth_type"]=> "cookie"
      ["controlhost"]=> "nginx-sql"
      ["controluser"]=> "phpmyadmin"
      ["controlpass"]=> "password"
      ["compress"]=> bool(false)
      ["AllowNoPassword"]=> bool(true)
    }
}
```

`nginx-sql` is hosting the control database. When I connect to that database in phpmyadmin, all features are enabled (history, persistent settings, etc.). However when I connect to `gitea-sql` I get the warning at the bottom of the screen that the control database doesn't exist. It offers to create the database and if I do, it creates it within `gitea-sql` and then I get the control features, but this isn't what I wanted.

I added some php to output $cfg using var_dump to file so I could confirm that the controlhost setting was bring passed to the config from docker. Now that I see that controlhost is filled, I don't understand why it isn't working.

phpmyadmin 5.0.1 via https://hub.docker.com/r/phpmyadmin/phpmyadmin/

**Comment by williamdes** [comment]
@stalks can you post your docker-compose file?

**Comment by stalks** [comment]
Sure.

```
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5.0.1-fpm-alpine
                container_name: phpmyadmin
                restart: unless-stopped
                depends_on:
                        - sql
                environment: 
                        PMA_ABSOLUTE_URI: https://example.com/phpmyadmin
                        PMA_HOSTS: nginx-sql,gitea-sql,phpipam-sql,powerdns-sql,seafile-sql,teamspeak3-sql,zabbix-sql
                        UPLOAD_LIMIT: 1G
                        PMA_CONTROLHOST: nginx-sql
                        PMA_CONTROLUSER: phpmyadmin
                        PMA_CONTROLPASS: password
                volumes:
                        - site-phpmyadmin:/var/www/html
                networks:
                        - web
                        - pma # for other sql containers
                        - sql
```

**Comment by williamdes** [comment]
can I have the `nginx-sql` block or short answer did you add a network alias ?
https://github.com/wdesportes/phpmyadmin-local-setup/blob/6e1e8c78e26326d28e119e011c951aa8e28da7a6/docker-compose.yml#L62 will help you

**Comment by stalks** [comment]
I didn't add an alias. I'm relying on the internal DNS being configured by docker for name resolution. The databases are accessible by name, as I am able to connect to them all in phpmyadmin, including nginx-sql.

phpmyadmin screenshot -- connected to nginx-sql:
![image](https://user-images.githubusercontent.com/1316058/73134294-dc7ade80-402c-11ea-8790-8328343e475d.png)

docker config for nginx-sql container:
```
       sql:
                image: mariadb:10.4
                container_name: nginx-sql
                environment:
                        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root-dbpasswd
                volumes:
                        - sql:/var/lib/mysql
                networks:
                        - sql
                secrets:
                        - root-dbpasswd
                healthcheck:
                        test: ["CMD", "mysqladmin" ,"ping", "-u", "healthcheck"]
                        timeout: 20s
                        retries: 10
```

**Comment by williamdes** [comment]
If you could post a full docker-compose file or add an example to my repository I could help you in a better way ;)

**Comment by stalks** [comment]
I've created a simple 3 container docker-compose file consisting of phpmyadmin 5.0.1 (full apache version) and 2x mariadb databases. In the ENV of phpmyadmin I have added the control variables and the first mariadb container creates the necessery user for phpmyadmin.

```yaml
version: '3.1'

services:
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5.0.1
                container_name: pma-example
                restart: unless-stopped
                depends_on:
                        - sql1
                        - sql2
                environment: 
                        PMA_HOSTS: sql1,sql2
                        PMA_CONTROLHOST: sql1
                        PMA_CONTROLUSER: pma
                        PMA_CONTROLPASS: pmapassword
                networks:
                        - net
                ports:
                        - 9191:80
        sql1:
                image: mariadb:10.4
                container_name: pma-example-sql1
                environment:
                        - MYSQL_ROOT_PASSWORD=insecurerootpassword
                        - MYSQL_DATABASE=phpmyadmin
                        - MYSQL_USER=pma
                        - MYSQL_PASSWORD=pmapassword
                networks:
                        - net
        sql2:
                image: mariadb:10.4
                container_name: pma-example-sql2
                environment:
                        - MYSQL_ROOT_PASSWORD=insecurerootpassword
                networks:
                        - net
networks:
        net:
                driver: bridge
```

My actions are:

1. docker-compose up

**Comment by stalks** [comment]
I have created a docker-compose file for a simple 3-container setup. phpmyadmin, sql1 and sql2. The intention is to use sql1 for the controlhost.

```yaml
version: '3.1'

services:
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:5.0.1
                container_name: pma-example
                restart: unless-stopped
                depends_on:
                        - sql1
                        - sql2
                environment: 
                        PMA_HOSTS: sql1,sql2
                        PMA_CONTROLHOST: sql1
                        PMA_CONTROLUSER: pma
                        PMA_CONTROLPASS: pmapassword
                networks:
                        - net
                ports:
                        - 9191:80
        sql1:
                image: mariadb:10.4
                container_name: pma-example-sql1
                environment:
                        - MYSQL_ROOT_PASSWORD=insecurerootpassword
                        - MYSQL_DATABASE=phpmyadmin
                        - MYSQL_USER=pma
                        - MYSQL_PASSWORD=pmapassword
                networks:
                        - net
        sql2:
                image: mariadb:10.4
                container_name: pma-example-sql2
                environment:
                        - MYSQL_ROOT_PASSWORD=insecurerootpassword
                networks:
                        - net
networks:
        net:
                driver: bridge
```

Steps taken are therefore:

1. `docker-compose up`
2. wait 20 seconds for mariadb to complete intialization
3. visit `http://dockerhost:9191/`
4. login as root to `pma-example-sql1`
5. at bottom of screen click "Find out why" (regarding missing database)
6. click to `Create `the database
7. click on home and note that there is no warning for missing control database
8. now log into `sql2`
9. phpmyadmin is requesting a control database and will even offer to create it -- however will create in sql2

Hopefully you can point out my error :) Thanks for taking the time to look into this.
