### ISSUE TITLE
5.0.4 Failed to set session cookie. Maybe you are using HTTP instead of HTTPS.

### ISSUE THREAD

**Issue by ericsssan** [phpmyadmin/phpmyadmin#16496]
Same here.
phpMyAdmin 5.0.4
Google App Engine Standard php74

config.inc.php: 

```php
$cfg['blowfish_secret'] = 'MAKSED'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

/*
 * Servers configuration
 */
$i = 0;

// Change this to use the project and instance that you've created.
$host = '/cloudsql/{{ MASKED }}';
$type = 'socket';

/*
* First server
*/
$i++;
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* Server parameters */
$cfg['Servers'][$i]['socket'] = $host;
$cfg['Servers'][$i]['connect_type'] = $type;
$cfg['Servers'][$i]['compress'] = false;
/* Select mysql if your server does not have mysqli */
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = false;
/*
 * End of servers configuration
 */

/*
 * Directories for saving/loading files from server
 */
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

/*
* Other settings
*/
$cfg['PmaNoRelation_DisableWarning'] = true;
$cfg['ExecTimeLimit'] = 60;
$cfg['CheckConfigurationPermissions'] = false;
$cfg['DefaultCharset'] = 'utf8mb4';
$cfg['TempDir'] = '/tmp';

```

app.yaml

```yml
service: phpmyadmin
runtime: php74

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 2

handlers:

  - url: /(.+\.(ico|jpg|png|gif|htm|html|css|js))$
    static_files: \1
    upload: (.+\.(ico|jpg|png|gif|htm|html|css|js))$

  - url: .*
    script: auto
    secure: always
```

php.ini

`google_app_engine.enable_functions = "php_uname, getmypid"`

_Originally posted by @ericsssan in https://github.com/phpmyadmin/phpmyadmin/issues/15634#issuecomment-732136164_

**Comment by williamdes** [comment]
Hi @ericsssan 
Does the login work sometimes or never ?

**Comment by ericsssan** [comment]
> Hi @ericsssan 
> 
> Does the login work sometimes or never ?

Hi @williamdes 

Never.

**Comment by williamdes** [comment]
Hi @ericsssan 

Oh okay, maybe a cookie domain issue. Would you mind emailing me a public URL to williamdes [at] wdes.fr ?

**Comment by williamdes** [comment]
This seems to be needed (untested)
Ref: https://github.com/gae-init/gae-init/issues/53#issuecomment-31730535
https://cloud.google.com/appengine/docs/standard/python/getting-started/serving-static-files
```yml
- url: /js/(.+\.php)$
  script: auto
  secure: always
  mime_type: text/javascript
```
