### ISSUE TITLE
Downloading a database with GZIP compression from PhpMyAdmin returns uncompressed files

### ISSUE THREAD

**Issue by Zio3D** [phpmyadmin/phpmyadmin#17413]
### Describe the bug

Since version 94.0.2 of Mozilla Firefox (64 bit) for Windows 10 64 bit, exporting a database with GZIP compression from PhpMyAdmin results in an uncompressed text file.
I report this bug to PhpMyAdmin because the ticket "https://bugzilla.mozilla.org/show_bug.cgi?id=1755324" on Firefox guides me to think about a PhpMyAdmin bug. 

### To Reproduce

1. With "Mozilla Firefox" (version greater than or equal to 94.0.2, for example 97.0.1) go to 'https://demo.phpmyadmin.net/STABLE/'.
2. On "Username:" field, insert 'root'. Press 'Go'.
3. Click on a database (for example 'egzamin ') and then in the top bar click 'Export'.
4. On "Export method:" select "Custom - display all possible options".
5. On "Compression:" select "gzipped".
6. Click "Go" at the bottom right of the page.
7. Save the file and then read with notepad (with notepad++ is more easy), it is result in .SQL format and not in compressed GZIP format.

### Expected behavior

The saved file must be a GZIP compressed .SQL file.

### Server configuration

- Web server: "nginx/1.14.2" ("https://demo.phpmyadmin.net/STABLE/")
- PHP version: 7.4.27.
- phpMyAdmin version: 5.1.3 (Git revision: f27346c from STABLE branch).

### Client configuration

- Browser: Mozilla Firefox 97.0.1
- Operating system: Windows 10 Pro 21H2 64 bit.

### Additional context

As I indicated in "### Describe the bug", I report this bug to PhpMyAdmin because the ticket "https://bugzilla.mozilla.org/show_bug.cgi?id=1755324" on Firefox guides me to think about a PhpMyAdmin bug.
It is strange that with the previous versions of Mozilla Firefox 94.0.2 the export worked correctly.

Thanks.

**Comment by williamdes** [comment]
Hi @Zio3D 
I am thinking this could be related to #16042 
Could you check ?

**Comment by Zio3D** [comment]
Hi @williamdes,
it is not related to #16042 as the file I downloaded is entirely in .SQL format.

**Comment by Zio3D** [comment]
I had my problems on "mysql.aruba.it".
Database Server:
- Server type: Percona Server
- Server version: 5.5.62-38.14-log - Percona Server (GPL), Release 38.14, Revision 7e0e1cc
- Protocol version: 10

With the test server "https://demo.phpmyadmin.net/STABLE" I have same problem but it only exports the first 74,824 Bytes.

**Comment by liviuconcioiu** [comment]
I can confirm what @Zio3D says. It exports only ~73 Kb (SQL only) and nothing else. Changing `application/x-gzip` with `application/octet-stream` fixes the problem.

Isn't possible to check if Firefox is present in user agent string and change `$mediaType` accordingly? Even if is a browser bug.

**Comment by williamdes** [comment]
Thanks for your comments, so this is a duplicate of #16042, right ?

**Comment by liviuconcioiu** [comment]
> Thanks for your comments, so this is a duplicate of #16042, right ?

Yes.

**Comment by williamdes** [comment]
Duplicate of #16042

**Comment by Zio3D** [comment]
@williamdes , can you reopen this issue?
This is not a duplicate of #16042.
Perhaps for @liviuconcioiu it is a duplicate. For me it remains a non-duplicate issue. On Aruba (mysql.aruba.it) the downloaded file is 500 MB uncompressed instead of the usual 80 MB compressed (GZIP).

**Comment by williamdes** [comment]
Could you try https://github.com/phpmyadmin/phpmyadmin/issues/16042#issuecomment-604159939 just in case ?

**Comment by Zio3D** [comment]
I'm sorry but I can't do this because the pages are managed by aruba.it.

**Comment by maciej-laskowski** [comment]
This can also be reproduced using docker. This gives you control over phpmyadmin version and allow to edit its files.

In empty directory create `docker-compose.yml` file
```
version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  db:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
```
run `docker-compose up -d`

go to `localhost:8000`
