### ISSUE TITLE
PHPMyAdmin default login details

### ISSUE THREAD

**Issue by Emeka212** [phpmyadmin/phpmyadmin#17696]
Hello, so I install PHPMyAdmin on docker (tho am using Caprover for this), but after installing PHPMyAdmin successfully, I was not able to log in cus I don't know the default server name, username, and password.

this is the image of PHPmyadmin

![screencapture-phpmyadmin-caprover-axxellanceblog-ml-index-php-2022-08-26-23_30_09](https://user-images.githubusercontent.com/60589175/186999016-6671a5a8-d0a9-41a5-9061-2b1e35d9b0a3.png)

my server is using arm and it's a ubuntu server, please I need help in resolving this issue.
Thanks in advance

and this is the Caprover .yml file I use in installing this

```yml
captainVersion: 4
services:
    $$cap_appname:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_ARBITRARY: '1'
            UPLOAD_LIMIT: $$cap_upload_limit
caproverOneClickApp:
    variables:
        - id: $$cap_upload_limit
          label: File size upload limit
          description: It will override the default value for apache and php-fpm inside the container. Default size is 2M
          defaultValue: 2M
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_pma_version
          label: PHP My Admin Version Tag
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/phpmyadmin/phpmyadmin/tags/
          defaultValue: 5.0.2
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            PhpMyAdmin is the most popular web interface for MySQL & MariaDB. Simply install PhpMyAdmin and then select what database you want to connect to.
            Enter your PhpMyAdmin Configuration parameters and click on next. It will take about a minute for the process to finish.
        end: >-
            PhpMyAdmin is deployed and available as $$cap_appname. 
            Note: Once deployed you can easily change the upload limit file size by modifying the value in the variable in the menu: App Configs>UPLOAD_LIMIT.
            If you need to upload files bigger than 500M you will also need to modify the option: 'client_max_body_size 500m' by clicking in the menu: HTTP Settings>Edit Default Nginx Configurations.
    displayName: phpMyAdmin
    isOfficial: true
    description: phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web
    documentation: Taken from https://hub.docker.com/r/phpmyadmin/phpmyadmin/
```

have I asked this on caprover repo? => Yes I have and I was told this was phpmyadmin issue and I should ask that here.
Please I need answers.
