### ISSUE TITLE
Moving columns causes the default uuid() value to get quotes around it

### ISSUE THREAD

**Issue by Nefcanto** [phpmyadmin/phpmyadmin#18006]
### Describe the bug

When I set a default value for a column that is `UUID` to `uuid()`, and use PHPMyAdmin to move it in the list of columns, and then use `show create table X`, I see that the `uuid()` would become `'uuid()'` and if I move it one more time, it becomes `'''uuid()'''`.

### To Reproduce

- Create a table with at least 3 columns
- Set two columns data types to be UUID
- Set default values for those two columns to `uuid()`
- Then use `Move column` feature to change the order of columns
  - Select the table
  - Go to `Structure` tab
  - Use `Move column` link (if you can't find it, search it inside the page)
- Then use `show create table X`
- You should see quotes around the default value
- If you move columns multiple times, then those quotes will increase in number

### Expected behavior

The default value `uuid()` should remain as is when we move columns (change the order of columns)

### Screenshots

From left hand (default state) we get to the right hand after moving columns around

![Screenshot from 2023-01-07 16-19-15](https://user-images.githubusercontent.com/12782347/211151415-0fa0f48e-220c-4148-a017-c8d16c0ea1bd.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version: MariaDB
- phpMyAdmin version: latest

### Client configuration

- Browser: Chrome
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Hi @Nefcanto 
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) ?

Some UUID changes where made recently: https://github.com/phpmyadmin/phpmyadmin/issues?q=+milestone%3A5.2.1+is%3Aclosed+uuid+

**Comment by Nefcanto** [comment]
@williamdes yes sure. Thank you for responding so fast. I'll try with the 5.2 snapshot's non official docker image and I'll report the results here.

**Comment by Nefcanto** [comment]
@williamdes I tested using `botsudo/phpmyadmin-snapshots:5.3-snapshot` and this bug still exists.

This is my `docker-compose.yml` related to phpMyAdmin:

```
    pma:
        image: botsudo/phpmyadmin-snapshots:5.3-snapshot
        container_name: FalconPma
        restart: always
        logging:
            driver: none
        ports:
            - 7202:80
        environment: 
            - PMA_HOST=database     
        networks:
            - FalconNetwork
```
