### ISSUE TITLE
Feature: add a toggler element to switch between color schemes

### ISSUE THREAD

**Issue by adorade** [phpmyadmin/phpmyadmin#18246]
### Is your feature request related to a problem? Please describe.

The feature request is related to #16969 (How can I change scheme for Metro theme?) and #16868 (Add a select field for Metro color schemes).

Bootstrap v5.3.0-alpha now supports color modes or themes.
I added new color schemes in my BooDark theme, like in Metro.
There is currently no way to change the color schemes in the GUI.

### Describe the solution you'd like

To allow users to switch between color schemes, a toggle element will need to be created.

### Describe alternatives you've considered

Right now, only solution is that described [in this comment](https://github.com/phpmyadmin/phpmyadmin/issues/16969#issuecomment-864187054)

### Additional context

- phpMyAdmin version:  5.2.1
- BooDark versions: 1.1.0 (latest release)

**Comment by williamdes** [comment]
> To allow users to switch between color schemes, a toggle element will need to be created.

And not only that, the spec of `theme.json` should also make this part possible

/cc @MauricioFauth

**Comment by ibennetch** [comment]
I think there's something called a "scheme" to allow themes to have multiple color variations. Metro (IIRC) used this, at least used to back in 4.9. I suspect it still does but I'm on mobile at the moment so it's hard to check.

It presents as an extra bit of text near the theme selector on the main page, a toggle between available schemes.

I don't recall implementation details off hand but remember it was used well by some themes.

Perhaps that's what you're looking for?

**Comment by williamdes** [comment]
IIRC the scheme implementation is hard coded for the Metro theme
Is that what we discussed @MauricioFauth?

**Comment by adorade** [comment]
Right now, color schemes in Metro are generated like this:

```scss
// themes/metro/scss/_variables.scss
// Theme color scheme
// Values: "teal", "redmond", "blueeyes", "mono", "win"
// Default: "win"
// Set this value for the desired color scheme
$color-scheme: win !default;

// scss variables for "win" color scheme

@if $color-scheme == teal {
  // scss variables changed for "teal"
} @else if $color-scheme == redmond {
  // scss variables changed for "redmond"
} @else if $color-scheme == blueeyes {
  // scss variables changed for "blueeyes"
} @else if $color-scheme == mono {
  // scss variables changed for "mono"
}

// themes/metro/scss/teal-theme.scss
$color-scheme: teal;
@import "theme";

// the same for the rest of color schemes
// redmond-theme.scss, blueeyes-theme.scss, mono-theme.scss, 
```

After you run `yarn run css-compile` 5 files are generated, one for each color scheme.
In order to be able to use the desired scheme, the files must be renamed, like this:

```sh
mv themes/metro/css/theme.css themes/metro/css/win-theme.css
mv themes/metro/css/mono-theme.css themes/metro/css/theme.css
```

In BooDark I use the same approach, only I change one `scss` variable

**Comment by adorade** [comment]
The way the color scheme is approached in Bootstrap 5.3.0-alpha is different, and using `css custom properties (variables)` the solution could be something like the following:

```scss
// BooDark theme
// themes/boodark/scss/_root.scss
:root {
  @media (prefers-color-scheme: cyan) {
    color-scheme: dark;
    --my-css-variable: $pma-cyan;
    // other css variables here
  }

  @media (prefers-color-scheme: teal) {
    color-scheme: dark;
    --my-css-variable: $pma-teal;
    // other css variables here
  }

  @media (prefers-color-scheme: nord) {
    color-scheme: dark;
    --my-css-variable: $pma-nord;
    // other css variables here
  }

  @media (prefers-color-scheme: orange) {
    color-scheme: dark;
    --my-css-variable: $pma-orange;
    // other css variables here
  }
}
```

`CSS custom properties (variables)` can be used afterwards in any `scss` file.
After you run `yarn run css-compile` only 1 file are generated: `theme.scss`.
And then, using a toggle button, you can change the theme scheme.

I will try in the coming days to come up with a concrete example (html, js and css), which will work, based on the BooDark theme.
