### ISSUE TITLE
Phpmyadmin not working on browser with warden docker.

### ISSUE THREAD

**Issue by RakeshJesadiya** [phpmyadmin/phpmyadmin#18371]
### Describe the bug

I am running warden to local development of my Magento projects. I am using PHPMyAdmin to check database-related stuff.
I am using Warden https://github.com/wardenenv/warden from the link.

I have just upgraded Warden in my Linux Ubuntu 20.04 and after that, I am not able to access phpmyadmin from the browser but able to access it from the Command line tools (CLI).

I get an error, **MySQL said: Documentation
Cannot connect: invalid settings.**

### To Reproduce

I have added the Phpmyadmin configuration via the warden-env.yml file.
```
version: "3.5"
services:
  php-fpm:
    ports:
      - "4000:4000"
      - "3001:3001"
  phpmyadmin:
    restart: always
    image: docker.io/library/phpmyadmin:latest
    hostname: ${WARDEN_ENV_NAME}-phpmyadmin
    domainname: phpmyadmin.${WARDEN_ENV_NAME}.test
    ports:
      - 9200:80
    environment:
      - PMA_HOSTS=${WARDEN_ENV_NAME}_db_1
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - PMA_ABSOLUTE_URI=http://phpmyadmin.${TRAEFIK_DOMAIN}
```

### Expected behavior

If I go with CLI tools, I am able to access database with CLI.

When you hit the URL from the browser it will show phpmyadmin GUI, http://0.0.0.0:9200/index.php

Earlier it was working fine but suddenly it stopped working.

### Screenshots
![phpmyadmin](https://user-images.githubusercontent.com/18594535/235064344-02bde63c-f7ad-4a43-9e14-5917cfdc3b85.jpg)
