### ISSUE TITLE
6.0 - The code font size is smaller compared to 5.2

### ISSUE THREAD

**Issue by xPaw** [phpmyadmin/phpmyadmin#19489]
5.2:
![image](https://github.com/user-attachments/assets/3953dbcd-e1cb-4209-a7a1-87c374a04d9c)

6.0:
![image](https://github.com/user-attachments/assets/2d3ea2b3-5bef-44af-ab3c-46d8957d4229)

Don't know if this was an intentional change, but I find the font size too small now (it's less than 12px), and the padding around sql queries is gone.

**Comment by williamdes** [comment]
Thank you for reporting this !

**Comment by jshaofa-ui** [comment]
## Proposed Fix: Code Font Size Regression

### Root Cause
phpMyAdmin 6.0 introduced a new UI framework. During the migration, the monospace/code font size was reduced from the 5.2 default (~14px) to a smaller value (~12px or less).

### Fix

**File: `css/themes/bootstrap-5.css` (or the active theme CSS file)**

```css
/* Add/modify the following rules to restore 5.2 code font size */

:root {
    /* Restore monospace font size to 5.2 default */
    --font-size-monospace: 14px;
}

/* Ensure all code/editor elements use the correct size */
.cm-editor,
.cm-editor .cm-scroller,
.CodeMirror,
.code,
pre,
textarea.code,
textarea.monospace,
.sql,
pre.sql,
.result_query .sql,
.result_query pre {
    font-size: var(--font-size-monospace, 14px) !important;
}

/* Also fix inline code in tables */
td.code,
td.monospace {
    font-size: var(--font-size-monospace, 14px);
}
```

### Alternative: Precise CSS Variable Fix
If the theme uses CSS custom properties:
```css
/* Find and update the monospace font-size variable */
:root {
    --bs-body-font-size: 1rem;
    --font-size-monospace: 0.875rem; /* 14px — was likely set to 0.75rem (12px) */
}
```

### Verification
1. Open phpMyAdmin 6.0
2. Navigate to SQL editor or any code display area
3. Compare font size with phpMyAdmin 5.2 — should match
