### ISSUE TITLE
[Bug]: Duplicated Set-Cookie headers causing NGINX proxy to fail

### ISSUE THREAD

**Issue by ulexxander** [phpmyadmin/phpmyadmin#19702]
### Describe the bug

It seems that after executing statements on `SQL` page phpmyadmin returns same duplicated `Set-Cookie` header line for each statement in submitted query.

This makes HTTP response header big if you have a lot of SQL statements.

In our case it started to cause errors `upstream sent too big header while reading response header from upstream` in our reverse proxy, which is Kubernetes Ingress NGINX Controller.

We use `phpmyadmin:5.2.1-apache` Docker image.

Workaround I used is to increase `proxy-buffer-size` in ingress config for phpmyadmin:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  annotations:
    # Workaround for "upstream sent too big header while reading response header from upstream"
    # https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k" # Default: 4k
```

### How to Reproduce

1. Go to `/server/sql` page and submit multiple SQL statements
2. Check response of `/import` in browser network tab - it will have multiple `Set-Cookie` header lines with same values

### Expected behavior

I expected to not have duplicated `Set-Cookie` headers.

### Screenshots

Example: response headers of `/import`

![Image](https://github.com/user-attachments/assets/b7bd710d-f491-423d-b013-052bb81ec5f0)

### Operating System

Linux

### Web Server

Apache/2.4.62 (Debian)

### Database Server

MySQL

### Database version

8.0.41

### PHP version

8.2.26

### phpMyAdmin version

5.2.1

### browser

Firefox/138.0
